version: '2.1'

services:
  ts280_data_bridge:
    build: ./
    hostname: ts280_data_bridge
    container_name: ts280_data_bridge
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "10"
    ports:
      - 8080:8080
    networks:
      - cityiot_bridge_network


networks:
  cityiot_bridge_network: