version: '3'

services:
  ts280_data_bridge:
    build: ./
    hostname: ts280_data_bridge
    container_name: ts280_data_bridge
    expose:
      - "8080"
    networks:
      - cityiot_bridge_network


networks:
  cityiot_bridge_network: